# Dependabot will run on day 22 of each month at 03:58 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "58 3 22 * *"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "58 3 22 * *"
    open-pull-requests-limit: 20
    assignees:
      - "klein0r"
    versioning-strategy: "increase"
